name: Build 32-bit Program

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 使用最新的Python 3版本

      - name: Install dependencies
        run: |
          pip install requests tqdm

      - name: Install PyInstaller
        run: |
          python -m pip install pyinstaller

      - name: Build 32-bit Program
        run: |
          python -m venv venv
          venv\Scripts\activate
          python -m pip install pyinstaller
          python -m pyinstaller --noconfirm --assume-yes --onedir --arch=386 test.py

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: 32bit_program
          path: dist/
