name: Build and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        architecture: x86
        python-version: 3.x

    - name: Install Dependencies
      run: |
        pip install requests tqdm

    - name: Build
      run: pyinstaller --onedir test.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-files
        path: dist/
