name: Build Python Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install requests tqdm

    - name: Build 32-bit Version
      run: py -m PyInstaller --distpath dist/win32 --onefile --arch 32 test.py

    - name: Build 64-bit Version
      run: py -m PyInstaller --distpath dist/win64 --onefile --arch 64 test.py

    - name: Upload Artifacts
      uses
