name: Python CI

on:
  push:
    branches: [ master ]  # 当 master 分支有新的代码提交时触发

jobs:
  build:

    runs-on: windows-latest  # 使用最新的 Windows 操作系统

    steps:
    - uses: actions/checkout@v2  # 检出代码到 GitHub Actions

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 选择最新的 Python 版本，比如 '3.9'，注意：根据实际情况修改 'x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装项目依赖，根据您的需求修改该命令
        pip install requests tqdm tkinter

    - name: Build
      run: |
        python build.py  # 替换为您的构建命令，比如编译 Python 程序或生成可执行文件

    - name: Test
      run: |
        python run_tests.py  # 替换为您的测试命令，比如运行单元测试

    # 如果有其他操作或需要发布程序，请添加相应的步骤
