name: test Windows win7+
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Create Executable
        run: pyinstaller -D test.py

      - name: Download 7-Zip
        run: |
        curl -sS -o 7z.zip https://www.7-zip.org/a/7z1900-x64.zip
        Expand-Archive -Path 7z.zip -DestinationPath 7z
        $env:PATH += ";$(PWD)/7z"

      - name: Compress to ZIP
        run: |
          7z a -tzip test.zip dist/
