name: test Windows win7+
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Create Executable
        run: pyinstaller -D test.py

      # 压缩到ZIP（使用PowerShell的Compress-Archive命令）  
      - name: Compress to ZIP  
        run: |  
          # 切换到包含dist文件夹的目录（如果当前目录不是的话）  
          cd $(Build.Repository.LocalPath)  
            
          # 使用PowerShell的Compress-Archive命令压缩dist文件夹  
          PowerShell -Command "Compress-Archive -Path './dist/*' -DestinationPath './test.zip'"  

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-zip
          path: test.zip
