name: Build and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests tqdm pyinstaller

      - name: Build 64-bit binary
        run: |
          python -m py_compile test.py
          pyinstaller --distpath build --name Zesigen-Download-Manager.exe -D -F test.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows 64-bit
          path: build/Zesigen-Download-Manager.exe
